# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build_Server
    displayName: Build_ios
    steps:
    
    # - script: |
    #     xcode-select -p
    
    
    
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'Certificates.p12'
        certPwd: $(certpass)
        keychain: 'temp'
        
        
    # - task: InstallAppleProvisioningProfile@1
    #   inputs:
    #     provisioningProfileLocation: 'secureFiles'
    #     provProfileSecureFile: 'htftd'
    
    - script: |
        npm install i -g @ionic/cli
        ionic cap build ios --prod


    - task: Xcode@5
      inputs:
        actions: 'build archive'
        packageApp: true
        xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
        archivePath: '$(Build.ArtifactStagingDirectory)'
        signingOption: 'auto'
        xcodeVersion: default

    - task: PublishPipelineArtifact@1
      inputs:
          targetPath: '$(Pipeline.Workspace)/a'
          publishLocation: 'pipeline' 